services:
  suicide-detection:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false
      - TRANSFORMERS_OFFLINE=0
      - HF_HOME=/app/.cache/huggingface
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: "2"
        reservations:
          memory: 3G
          cpus: "1"
    mem_limit: 6g
    mem_reservation: 3g
